version: "3.9"

services:
  chatapp:
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        environment: "${NODE_ENV}"
    container_name: "chat_app"
    ports:
      - ${PORT_CLIENT}:5173
      - ${PORT_SERVER}:3000
    volumes:
      - ./package.json:/chatapp/package.json
      - ./app:/chatapp/app
      - ./server:/chatapp/server
      - ./shared:/chatapp/shared
      - ./bin:/chatapp/bin
    environment:
      VITE_SERVER_URL: "http://localhost:${PORT_SERVER}"
      CLIENT_URL: "http://localhost:${PORT_CLIENT}"
      REDIS_URI: "redis://redis:${PORT_REDIS}"
      MONGO_CON_STRING: "mongodb://mongo:${PORT_MONGO}/chatapp"

  mongo:
    image: mongo
    container_name: "chat_app_mongo"
    restart: always
    ports:
      - ${PORT_MONGO}:27017

  redis:
    image: redis:6.2-alpine
    container_name: "chat_app_redis"
    restart: always
    ports:
      - ${PORT_REDIS}:6379