version: "3.9"

services:
  chatapp:
    build: ./
    image: "chat_app"
    container_name: "chatapp"
    ports:
      - ${PORT_CLIENT}:5173
      - ${PORT_SERVER}:3000
    volumes:
      - ./package.json:/chatapp/package.json
      - ./app:/chatapp/app
      - ./server:/chatapp/server
      - ./shared:/chatapp/shared
    environment:
      VITE_SERVER_URL: "http://${HOST_SERVER}:${PORT_SERVER}"
      CLIENT_URL: "http://${HOST_CLIENT}:${PORT_CLIENT}"
      REDIS_CON_STRING: "redis://redis:6379"
      MOGODB_CON_STRING: "mongodb://mongo:27017/chatapp"

  mongo:
    image: mongo
    container_name: "chat_app_mongo"
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis:6.2-alpine
    container_name: "chat_app_redis"
    restart: always
    ports:
      - "6379:6379"
