version: "3.9"

services:
  chatapp:
    tty: true
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        environment: "${NODE_ENV}"
    container_name: "chat_app"
    ports:
      - ${PORT_CLIENT}:5173
      - ${PORT_SERVER}:3000
    volumes:
      - ./package.json:/chatapp/package.json
      - ./app:/chatapp/app
      - ./server:/chatapp/server
      - ./shared:/chatapp/shared
      - ./bin:/chatapp/bin
    environment:
      VITE_SERVER_URL: "http://localhost:${PORT_SERVER}"
      REDIS_URI: "redis://redis:6379"
      MONGO_URI: "mongodb://mongo:27017/chatapp"
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET}
      NODE_ENV: ${NODE_ENV}

  mongo:
    image: mongo
    container_name: "chat_app_mongo"
    restart: always
    logging:
      driver: "none"

  redis:
    image: redis:6.2-alpine
    container_name: "chat_app_redis"
    restart: always
    logging:
      driver: "none"
