version: "3.9"

services:

  chatapp:
    build: ./
    container_name: "chatapp"
    ports:
     - '5173:5173'
     - '3000:3000'
    volumes: 
      - ./tsconfig.json:/chatapp/tsconfig.json
      - ./app:/chatapp/app
      - ./server:/chatapp/server
      - ./shared:/chatapp/shared
      - ./package.json:/chatapp/package.json