services:
  chatapp:
    tty: true
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        environment: "${NODE_ENV}"
    container_name: "chat_app"
    ports:
      - ${PORT_CLIENT}:5173
      - ${PORT}:3000
      - 3001:3001
    volumes:
      - ./package.json:/chatapp/package.json
      - ./package-lock.json:/chatapp/package-lock.json
      - ./tsconfig.json:/chatapp/tsconfig.json
      - ./app:/chatapp/app
      - ./server:/chatapp/server
      - ./shared:/chatapp/shared
      - ./bin:/chatapp/bin
    environment:
      VITE_APP_DOMAIN: "localhost"
      VITE_APP_URL: "http://localhost:${PORT_CLIENT}"
      VITE_SERVER_URL: "http://localhost:${PORT}"
      REDIS_URI: "redis://redis:6379"
      MONGO_URI: "mongodb://mongo:27017/chatapp"
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET}
      NODE_ENV: ${NODE_ENV}
      PASSKEY_PRIVATE_KEY: ${PASSKEY_PRIVATE_KEY}
      VITE_PASSKEY_PUBLIC_KEY: ${PASSKEY_PUBLIC_KEY}
      PASSKEY_API_URL: ${PASSKEY_API_URL}
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      VITE_GOOGLE_OAUTH_REDIRECT_URL: ${GOOGLE_OAUTH_REDIRECT_URL}
      PORT: ${PORT}

  mongo:
    image: mongo
    container_name: "chat_app_mongo"
    restart: always
    logging:
      driver: "json-file"

  redis:
    image: redis:6.2-alpine
    container_name: "chat_app_redis"
    restart: always
    logging:
      driver: "json-file"
