name: Continuous deployment

on:
    push:
      branches:
        - main
        
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install modules
        run: npm i

      - name: compile app
        run: npm run build

      - name: check for dist
        run: bash -c "(cd server && ls)"
        
      - run: bash -c "(cd shared && ls)"

      - run: bash -c "echo $(pwd)"
      
      - run: ls

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            push: true
            tags: vacekto/chat_app:latest
            build-args: 
              environment="production"
# docker hub further uses webhook to deploy image to Render.com
